version: '3.5'
services:
  jusan-compose-final:
    image: jusan-fastapi-final:latest
    restart: on-failure
    ports:
      - '8080:8080'
  jusan-nginx-final:
    image: nginx:mainline
    restart: on-failure
    ports:
      - '8787:80'
    volumes:
      - /home/zhanbolat.kulzhabek/Downloads/docker-compose-final/jusan-docker-mount.conf:/etc/nginx/conf.d/default.conf
      - /home/zhanbolat.kulzhabek/Downloads/docker-compose-final/jusan-docker-mount:/var/www/example
      - /home/zhanbolat.kulzhabek/Downloads/docker-compose-final/jusan-fastapi-final.conf:/etc/nginx/conf.d/jusan-fastapi-final.conf
    depends_on:
      - jusan-compose-final

